# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180410_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Quiz'),
        ),
    ]
