# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180410_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
