# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 23, 52, 29, 909255)),
        ),
    ]
