# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180416_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 17, 1, 10, 31, 448622)),
        ),
    ]
